
#tomcat
server:
  port: 9009

#spring  
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true
      
#mysql      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cerxuqzbpyku.ap-northeast-1.rds.amazonaws.com:3306/database-1?serverTimezone=Asia/Seoul
    username: admin
    password: qlsneksql1

#mybatis
mybatis:
  type-aliases-package: data.mapper, data.dto
  mapper-locations:
  - /mapper/**/*.xml        
